import { TipoTramite } from "../ct/types";

/**
 * Esqueleto de secciones por tipo de trámite, según
 * references/deteccion_y_estructura.md de la skill ct-cormacarena.
 * El generador solo produce los títulos (para no fingir una evaluación de
 * fondo); el contenido de cada sección lo redacta el analista o la skill.
 */
export const ESTRUCTURA_POR_TRAMITE: Record<TipoTramite, string[]> = {
  "Inicio concesión de aguas subterráneas (con vertimiento al suelo)": [
    "OBJETO Y RAZÓN DEL CONCEPTO TÉCNICO",
    "ANTECEDENTES",
    "LOCALIZACIÓN",
    "IDENTIFICACIÓN DEL PREDIO",
    "MARCO GEOLÓGICO E HIDROGEOLÓGICO REGIONAL",
    "ANÁLISIS DE LA INFORMACIÓN",
    "  Solicitante y legitimación",
    "  Uso del suelo y determinantes territoriales",
    "  Concesión de aguas subterráneas (caudal, prueba de bombeo, calidad, georreferenciación, vulnerabilidad)",
    "  Programa de Uso Eficiente y Ahorro del Agua (PUEAA)",
    "  Vertimiento de aguas residuales domésticas tratadas al suelo (Res. 699/2021, STARD, campo de infiltración)",
    "DESARROLLO DE LA VISITA",
    "REGISTRO FOTOGRÁFICO",
    "CONCEPTO TÉCNICO",
    "  Respecto al uso del suelo",
    "  Respecto a la disponibilidad de servicios públicos",
    "  Con relación a la solicitud del permiso de concesión de aguas subterráneas",
    "  Respecto al Programa de Uso Eficiente y Ahorro del Agua",
    "  Con relación al vertimiento de aguas residuales domésticas tratadas al suelo",
    "REQUERIMIENTOS",
    "RECOMENDACIONES",
  ],
  "Inicio concesión de aguas subterráneas (sin vertimiento)": [
    "OBJETO Y RAZÓN DEL CONCEPTO TÉCNICO",
    "ANTECEDENTES",
    "LOCALIZACIÓN",
    "IDENTIFICACIÓN DEL PREDIO",
    "MARCO GEOLÓGICO E HIDROGEOLÓGICO REGIONAL",
    "ANÁLISIS DE LA INFORMACIÓN",
    "  Solicitante y legitimación",
    "  Uso del suelo y determinantes territoriales",
    "  Concesión de aguas subterráneas (caudal, prueba de bombeo, calidad, georreferenciación, vulnerabilidad)",
    "  Programa de Uso Eficiente y Ahorro del Agua (PUEAA)",
    "DESARROLLO DE LA VISITA",
    "REGISTRO FOTOGRÁFICO",
    "CONCEPTO TÉCNICO",
    "  Respecto al uso del suelo",
    "  Respecto a la disponibilidad de servicios públicos",
    "  Con relación a la solicitud del permiso de concesión de aguas subterráneas",
    "  Respecto al Programa de Uso Eficiente y Ahorro del Agua",
    "REQUERIMIENTOS",
    "RECOMENDACIONES",
  ],
  "Inicio concesión aljibe + vertimiento al suelo": [
    "OBJETO Y RAZÓN DEL CONCEPTO TÉCNICO",
    "ANTECEDENTES",
    "LOCALIZACIÓN",
    "IDENTIFICACIÓN DEL PREDIO",
    "MARCO GEOLÓGICO E HIDROGEOLÓGICO REGIONAL",
    "ANÁLISIS DE LA INFORMACIÓN",
    "  Solicitante y legitimación",
    "  Uso del suelo y determinantes territoriales",
    "  Concesión de aguas subterráneas - aljibe (prueba de bombeo simplificada, calidad, vulnerabilidad)",
    "  Programa de Uso Eficiente y Ahorro del Agua (PUEAA simplificado, Art. 3 Res. 1257/2018)",
    "  Vertimiento de aguas residuales domésticas tratadas al suelo (Res. 699/2021, STARD, campo de infiltración)",
    "DESARROLLO DE LA VISITA",
    "REGISTRO FOTOGRÁFICO",
    "CONCEPTO TÉCNICO",
    "  Respecto al uso del suelo",
    "  Respecto a la disponibilidad de servicios públicos",
    "  Con relación a la solicitud del permiso de concesión de aguas subterráneas",
    "  Respecto al Programa de Uso Eficiente y Ahorro del Agua",
    "  Con relación al vertimiento de aguas residuales domésticas tratadas al suelo",
    "REQUERIMIENTOS",
    "RECOMENDACIONES",
  ],
  "Prospección / exploración": [
    "OBJETO Y RAZÓN DEL CONCEPTO TÉCNICO",
    "ANTECEDENTES",
    "LOCALIZACIÓN",
    "IDENTIFICACIÓN DEL PREDIO",
    "MARCO GEOLÓGICO E HIDROGEOLÓGICO REGIONAL",
    "ANÁLISIS DE LA INFORMACIÓN (viabilidad de perforar: geofísica SEV, determinantes, restricciones, profundidad máxima, métodos, NTC 5539)",
    "DESARROLLO DE LA VISITA",
    "REGISTRO FOTOGRÁFICO",
    "CONCEPTO TÉCNICO",
    "REQUERIMIENTOS",
    "RECOMENDACIONES",
  ],
  "Evaluación de requerimientos (EvReq)": [
    "OBJETO Y RAZÓN DEL CONCEPTO TÉCNICO",
    "ANTECEDENTES",
    "EVALUACIÓN DE REQUERIMIENTOS (punto por punto del CT anterior)",
    "CONCEPTO TÉCNICO",
    "REQUERIMIENTOS (los que persisten)",
    "RECOMENDACIONES",
  ],
  "Control y seguimiento (CyS)": [
    "OBJETO Y RAZÓN DEL CONCEPTO TÉCNICO",
    "ANTECEDENTES",
    "DESARROLLO DE LA VISITA DE CONTROL Y SEGUIMIENTO",
    "VERIFICACIÓN DE CUMPLIMIENTO (medidor, caudal real vs. concesionado, infraestructura, avance PUEAA)",
    "REGISTRO FOTOGRÁFICO",
    "CONCEPTO TÉCNICO (conforme / no conforme / con observaciones)",
    "REQUERIMIENTOS",
    "RECOMENDACIONES",
  ],
  "Pre-visita (concepto de gabinete)": [
    "OBJETO Y RAZÓN DEL CONCEPTO TÉCNICO",
    "ANTECEDENTES",
    "EVALUACIÓN DOCUMENTAL (sin visita)",
    "CONCEPTO TÉCNICO (recomendaciones para la visita / requerimientos previos)",
    "RECOMENDACIONES",
  ],
  "Práctica de pruebas (sancionatorio)": [
    "OBJETO Y RAZÓN DEL CONCEPTO TÉCNICO",
    "ANTECEDENTES (Auto probatorio)",
    "CARGOS FORMULADOS Y VERIFICACIÓN EN VISITA",
    "DESARROLLO DE LA VISITA",
    "REGISTRO FOTOGRÁFICO",
    "CONCEPTO TÉCNICO (constatación de hechos; no absuelve los cargos)",
    "RECOMENDACIONES",
  ],
  "Recurso de reposición": [
    "OBJETO Y RAZÓN DEL CONCEPTO TÉCNICO",
    "ANTECEDENTES (CT/Resolución que negó y recurso presentado)",
    "ANÁLISIS DE LA NUEVA INFORMACIÓN APORTADA",
    "RE-EVALUACIÓN",
    "CONCEPTO TÉCNICO (si subsana o no las deficiencias del CT original)",
    "RECOMENDACIONES",
  ],
};
